CLOUD-2136 upgrade to 7.1.1.ER1
jboss-container-images/jboss-datagrid-7-image pull request #18
Opened 2017-10-25 15:45 UTC by bdecoste

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2017-10-26 07:38 UTC, slaskawi requested changes

2017-10-26 07:38 UTC, slaskawi commented on modules/datagrid/module.yaml
> -    - script: install_patches.sh
@bdecoste Could you please remove this files as well?

2017-10-26 09:57 UTC, goldmann requested changes

2017-10-26 09:57 UTC, goldmann commented on image.yaml
> +version: "7.1.1.ER1"
This should be `7.1.1`.

2017-10-26 09:57 UTC, goldmann commented on image.yaml
> +      value: "7.1.1.ER1"
This should be `7.1.1.GA`.

2017-10-26 09:57 UTC, goldmann commented on image.yaml
> +      description: "http://download-node-02.eng.bos.redhat.com/devel/candidates/JDG/JDG-7.1.1.ER1/jboss-datagrid-7.1.1.ER1-server.zip"
This should not be exposed/added. This is an internal link.

2017-12-06 08:50 UTC, slaskawi commented
Should be closed in favor of https://github.com/jboss-container-images/jboss-datagrid-7-image/pull/24. See https://issues.jboss.org/browse/CLOUD-2136.

2017-12-06 08:55 UTC, goldmann commented
Will be done as part #24.

2017-12-06 08:55 UTC, closed without merging